communicator:
  verbose: False
debug:
  debug_mode: False
  validation_mode: False
encoder:
  precision_bits: 16
functions:
  max_method: "log_reduction"

  # exponential function
  # exp_method: "limit"
  exp_method: "bior"
  exp_iterations: 8
  exp_haar_size_bits: 10
  exp_bior_size_bits: 5
  exp_lut_max_bits: 4
  exp_all_neg: True
  exp_neg_lut_size: 256 # 2^8

  # log configuration
  # log_method: "iter"
  log_method: "bior"
  log_iterations: 2
  log_exp_iterations: 8
  log_order: 8
  log_haar_size_bits: 10
  log_bior_size_bits: 8
  log_lut_max_bits: 4

  # reciprocal configuration
  # reciprocal_method: "NR"
  reciprocal_method: "bior"
  reciprocal_nr_iters: 10
  reciprocal_log_iters: 1
  reciprocal_all_pos: True
  reciprocal_initial: null
  reciprocal_haar_size_bits: 12
  reciprocal_bior_size_bits: 8
  reciprocal_lut_max_bits: 6

  # sqrt configuration
  # sqrt_method: "NR"
  sqrt_method: "bior"
  sqrt_nr_iters: 3
  sqrt_nr_initial: null
  sqrt_haar_size_bits: 10
  sqrt_bior_size_bits: 6
  sqrt_lut_max_bits: 4

  # inv_sqrt configuration
  # inv_sqrt_method: "NR"
  inv_sqrt_method: "bior"
  inv_sqrt_haar_size_bits: 10
  inv_sqrt_bior_size_bits: 10
  inv_sqrt_lut_max_bits: 4

  # sigmoid / tanh configuration
  # sigmoid_tanh_method: "reciprocal"
  sigmoid_tanh_method: "bior"
  sigmoid_tanh_terms: 32
  sigmoid_tanh_haar_size_bits: 10
  sigmoid_tanh_bior_size_bits: 6
  sigmoid_lut_max_bits: 4 # [-16, 16]
  tanh_lut_max_bits: 3 # [-8, 8]

  # trigonometry configuration
  # trigonometry_method: "NR"
  trigonometry_method: "bior"
  trigonometry_haar_size_bits: 8
  trigonometry_bior_size_bits: 5
  trig_iterations: 10

  # error function configuration:
  # erf_method: "Taylor"
  erf_method: "bior"
  erf_iterations: 8
  erf_haar_size_bits: 10
  erf_bior_size_bits: 5
  erf_lut_max_bits: 2 # [-4, 4]

  # gelu configuration:
  # gelu_method: "erf"
  gelu_method: "bior"
  gelu_haar_size_bits: 7
  gelu_bior_size_bits: 4
  gelu_lut_max_bits: 2

  # silu configuration:
  # silu_method: "sigmoid"
  silu_method: "bior"
  silu_haar_size_bits: 7
  silu_bior_size_bits: 4
  silu_lut_max_bits: 4 # [-16, 16]
mpc:
  active_security: False
  provider: "TFP"
  protocol: "beaver"
nn:
  dpsmpc:
    protocol: "layer_estimation"
    skip_loss_forward: True
    cache_pred_size: True
