communicator:
  verbose: False
debug:
  debug_mode: False
  validation_mode: False
encoder:
  precision_bits: 16
functions:
  max_method: "log_reduction"

  # exponential function
  # exp_method: "limit"
  exp_method: "lut"
  exp_iterations: 8
  exp_lut_truncation_bits: 6
  exp_lut_max_element: 16 # 2^4
  exp_all_neg: True
  exp_neg_lut_size: 256 # 2^8

  # reciprocal configuration
  # reciprocal_method: "NR"
  reciprocal_method: "lut"
  reciprocal_nr_iters: 10
  reciprocal_log_iters: 1
  reciprocal_all_pos: False
  reciprocal_initial: null
  reciprocal_lut_truncation_bits: 6
  reciprocal_lut_max_element: 16 # 2^4

  # sqrt configuration
  # sqrt_method: "NR"
  sqrt_method: "lut"
  sqrt_nr_iters: 3
  sqrt_nr_initial: null
  sqrt_lut_truncation_bits: 10
  sqrt_lut_max_element: 16 # 2^4

  # inv_sqrt configuration
  # inv_sqrt_method: "NR"
  inv_sqrt_method: "lut"
  inv_sqrt_lut_truncation_bits: 10
  inv_sqrt_lut_max_element: 16 # 2^4

  # sigmoid / tanh configuration
  # sigmoid_tanh_method: "reciprocal"
  sigmoid_tanh_method: "lut"
  sigmoid_tanh_terms: 32
  sigmoid_lut_truncation_bits: 6
  sigmoid_lut_max_element: 16 # 2^4
  tanh_lut_truncation_bits: 6
  tanh_lut_max_element: 16 # 2^4

  # log configuration
  # log_method: "iter"
  log_method: "lut"
  log_iterations: 2
  log_exp_iterations: 8
  log_order: 8
  log_lut_truncation_bits: 6
  log_lut_max_element: 16 # 2^4
  
  # trigonometry configuration
  # trigonometry_method: "NR"
  trigonometry_method: "lut"
  trigonometry_lut_truncation_bits: 10
  trigonometry_lut_max_element: 16 # 2^4
  trig_iterations: 10

  # error function configuration:
  # erf_method: "Taylor"
  erf_method: "lut"
  erf_iterations: 8
  erf_lut_truncation_bits: 6
  erf_lut_max_element: 16 # 2^4
mpc:
  active_security: False
  provider: "TFP"
  protocol: "beaver"
nn:
  dpsmpc:
    protocol: "layer_estimation"
    skip_loss_forward: True
    cache_pred_size: True
